---
## KER - 6/23/2022
- name: filebeat Certificate Cleanup
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Removes wildcard_<my_domain>_com.bundle.old from /etc/filebeat/certs
      file:
        path: /etc/filebeat/certs/wildcard_<my_domain>_com.bundle.old
        state: absent