---
## KER - 8/01/2022
- name: filebeat version update
  hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Stop filebeat services
      ansible.builtin.service:
        name: apt
        state: stopped

    - name: Backup config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/filebeat/filebeat.yml
        dest: /etc/filebeat/filebeat.yml.ansible

    - name: Add filebeat repository
      ansible.builtin.yum_repository:
        name: filebeat
        description: filebeat yum repo
        baseurl: https://artifacts.elastic.co/packages/8.x/yum

    - name: Upgrades filebeat to latest version available to repo in /etc/yum.repo.d/elasticsearch.repo on target machine
      yum:
        name: filebeat
        enablerepo: elasticsearch
        state: latest

    - name: Remove filebeat repo
      ansible.builtin.yum_repository:
        name: elasticsearch
        state: absent

    - name: Restore config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/filebeat/filebeat.yml.ansible
        dest: /etc/filebeat/filebeat.yml
      become: yes

    - name: Restart filebeat service on centos, in all cases, also issue daemon-reload to pick up config changes
      ansible.builtin.systemd:
        state: started
        daemon_reload: yes
        name: filebeat