---
## KER - 6/22/2022
- name: Elasticsearch Certificate Cleanup
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Removes wildcard_clearsense_com.bundle.old from /etc/kibana
      file:
        path: /etc/kibana/wildcard_clearsense_com.bundle.old
        state: absent