filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /opt/<tool>/logs/<tool>.log*
      - /opt/<other_tool>/logs/<other_tool>.log*

    multiline.pattern: ^\[
    multiline.match: after

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false


setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

#-------------------------- KAFKA OUTPUT --------------------------------------
setup.template.enabled: false
output.kafka:
  hosts: ["kafka003.fivefingerheadpat.local:6667","kafka002.fivefingerheadpat.local:6667","kafka001.fivefingerheadpat.local:6667"]
  topic: "prod-<your_topic_here>-###TENANT###"
  codec.json:
    pretty: true


processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~