---
## KER - 8/01/2022
- name: metricbeat version update
  hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Stop metricbeat services
      ansible.builtin.service:
        name: apt
        state: stopped

    - name: Backup config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/metricbeat/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml.ansible

    - name: Add metricbeat repository
      ansible.builtin.yum_repository:
        name: metricbeat
        description: metricbeat yum repo
        baseurl: https://artifacts.elastic.co/packages/8.x/yum

    - name: Upgrades metricbeat to latest version available to repo in /etc/yum.repo.d/elasticsearch.repo on target machine
      yum:
        name: metricbeat
        enablerepo: elasticsearch
        state: latest

    - name: Remove metricbeat repo
      ansible.builtin.yum_repository:
        name: elasticsearch
        state: absent

    - name: Restore config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/metricbeat/metricbeat.yml.ansible
        dest: /etc/metricbeat/metricbeat.yml
      become: yes

    - name: Restart metricbeat service on centos, in all cases, also issue daemon-reload to pick up config changes
      ansible.builtin.systemd:
        state: started
        daemon_reload: yes
        name: metricbeat

    - name: Starting metricbeat Service
      ansible.builtin.service:
        name: metricbeat
        state: started