---
## KER - 7/22/2022
- name: metricbeat version update
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Stopping metricbeat services
      ansible.builtin.service:
        name: metricbeat
        state: stopped

    - name: Backup config files
        ansible.builtin.copy:
          remote_src: true
          src: /etc/metricbeat/metricbeat.yml
          dest: /etc/metricbeat/metricbeat.yml.ansible_bkp
        when: check_file_name.stat.exists

    - name: Rotate repo file to enable metricbeat downloads/updates
        ansible.builtin.copy:
          remote_src: true
          src: /etc/apt/sources.list.d/elastic-8.x.list.ansible
          dest: /etc/apt/sources.list.d/elastic-8.x.list
        when: check_file_name.stat.exists

    - name: Upgrades metricbeat to latest version available to repo in /etc/apt/sources.list.d/elastic-8.x.list on target machine
        ansible.builtin.apt:
          name: metricbeat
          allow_change_held_packages: true
          state: latest

    - name: restore config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/metricbeat/metricbeat.yml.ansible_bkp
        dest: /etc/metricbeat/metricbeat.yml
        owner: root
        group: root
        mode: '0644'
      when: check_file_name.stat.exists

    - name: Rotate repo file to disable metricbeat downloads/updates
      ansible.builtin.copy:
        remote_src: true
        src: /etc/apt/sources.list.d/elastic-8.x.list
        dest: /etc/apt/sources.list.d/elastic-8.x.list.ansible
    when: check_file_name.stat.exists

      - name: Starting metricbeat Service
        ansible.builtin.service:
          name: metricbeat
          state: started