---
### KER - 8/8/2022
- name: EDC Elasticsearch Integreation install
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: stop Zoomdata services
      ansible.builtin.shell: /opt/zoomdata/bin/zdmanage services stop

    - name: Copy RPM down from repo
      ansible.builtin.get_url:
        url: "https://composer-repo.logianalytics.com/8.1/yum/redhat/7/x86_64/stable/zoomdata-edc-elasticsearch-8.0-8.1.0-3.el7.stable.noarch.rpm"
        dest: /opt/zoomdata-edc-elasticsearch-7.0-8.0.0-3.el7.stable.noarch.rpm
        mode: 0755
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Copy DEB down from repo
      ansible.builtin.get_url:
        url: "https://composer-repo.logianalytics.com/8.1/apt/ubuntu/pool/stable/z/zoomdata-edc-elasticsearch-8.0/zoomdata-edc-elasticsearch-8.0_8.1.0-3+focal.stable_all.deb"
        dest: /opt/zoomdata-edc-elasticsearch-7.0_8.0.0-3+focal.stable_all.deb
        mode: 0755
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install package from download (redhat)
      ansible.builtin.yum:
        name: /opt/zoomdata-edc-elasticsearch-7.0-8.0.0-3.el7.stable.noarch.rpm
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install package from download (debian)
      ansible.builtin.apt:
        deb: /opt/zoomdata-edc-elasticsearch-7.0_8.0.0-3+focal.stable_all.deb
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: start Zoomdata services
      ansible.builtin.shell: /opt/zoomdata/bin/zdmanage services start