---
### KER - 8/8/2022
- name: EDC Elasticsearch Integreation install
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: stop Zoomdata services
      ansible.builtin.shell: /opt/zoomdata/bin/zdmanage services stop

    #- name: Remove EDC-Elasticsearch for redhat based clients
    #  ansible.builtin.yum_repository:
    #    name: zoomdata-edc-elasticsearch-7.0
    #    state: absent
    #  when: ansible_facts['os_family'] == 'RedHat'

    #- name: Remove EDC-Elasticsearch for debian based clients
    #  ansible.builtin.apt_repository:
    #    name: zoomdata-edc-elasticsearch-7.0
    #    state: absent
    #  when: ansible_facts['os_family'] == 'Debian'

    - name: Copy RPM down from repo
      get_url:
        url: "https://composer-repo.logianalytics.com/8.0/yum/redhat/7/x86_64/stable/zoomdata-edc-elasticsearch-7.0-8.0.0-3.el7.stable.noarch.rpm"
        dest: /opt/zoomdata-edc-elasticsearch-7.0-8.0.0-3.el7.stable.noarch.rpm
        mode: 0777
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Copy DEB down from repo
        get_url:
          url: "https://composer-repo.logianalytics.com/8.0/apt/ubuntu/pool/stable/z/zoomdata-edc-elasticsearch-7.0/zoomdata-edc-elasticsearch-7.0_8.0.0-3+focal.stable_all.deb"
          dest: /opt/zoomdata-edc-elasticsearch-7.0-8.0.0-3.el7.stable.noarch.rpm
          mode: 0777
        when: ansible_facts['os_family'] == 'Debian'

    - name: Install package from download (redhat)
      ansible.builtin.yum:
        name: /opt/zoomdata-edc-elasticsearch-7.0-8.0.0-3.el7.stable.noarch.rpm
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install package from download (debian)
      ansible.builtin.apt:
        name: /opt/zoomdata-edc-elasticsearch-7.0_8.0.0-3+focal.stable_all.deb
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    #- name: Install EDC-Elasticsearch v8 for redhat based clients
    #  ansible.builtin.yum:
    #    name: https://composer-repo.logianalytics.com/8.0/yum/redhat/7/x86_64/stable/zoomdata-edc-elasticsearch-7.0-8.0.0-3.el7.stable.noarch.rpm
    #    state: present
    #  when: ansible_facts['os_family'] == 'RedHat'

    #- name: Install EDC-Elasticsearch v8 for debian based clients
    #  ansible.builtin.apt:
    #    name: https://composer-repo.logianalytics.com/8.0/apt/ubuntu/pool/stable/z/zoomdata-edc-elasticsearch-7.0/zoomdata-edc-elasticsearch-7.0_8.0.0-3+focal.stable_all.deb
    #    state: present
    #  when: ansible_facts['os_family'] == 'Debian'

    - name: start Zoomdata services
      ansible.builtin.shell: /opt/zoomdata/bin/zdmanage services start