## KER - 6/22/2022
- name: Zoomdata Upgrade
  hosts: all
  gather_facts: false
  become: true
  vars:
    os_environment:
      - key: EDITOR
        value: vi
      - key: REPORTHOME
        value: /home/logij/ReportServer/

  tasks:
    - name: Create directory
      file:
        path: /home/logij/ReportServer/custom
        state: directory
        owner: root
        group: root
        mode: 0775

      - name: customize /etc/environment
        ansible.builtin.lineinfile:
          dest: "/etc/environment"
          state: present
          regexp: "^{{ item.key }}="
          line: "{{ item.key }}={{ item.value }}"
        with_items: "{{ os_environment }}"

      - name: Run Zoomdata service shutdown script
        ansible.builtin.script: /opt/zoomdata/bin/zdmanage services stop

      - name: Copy welcome.jsp with owner and permissions
         copy:
         src: /build/resources/main/public_html/welcome.jsp
         dest: /home/logij/ReportServer/public_html/jinfonet/welcome.jsp
         owner: root
         group: root
         mode: '0644'

        - name: Copy executeLogin.jsp with owner and permissions
            copy:
            src: /build/resources/main/public_html/executeLogin.jsp
            dest: /home/logij/ReportServer/public_html/executeLogin.jsp
            owner: root
            group: root
            mode: '0644'

         - name: Copy application.properties with owner and permissions
             copy:
             src: configs/{{ environment }}/application.properties
             dest: /home/logij/ReportServer/bin/application.properties
             owner: root
             group: root
             mode: '0644'
#################################NEEDS VERIFICATION##########################################################
         - name: Copy logireports-sso.jar with owner and permissions
             copy:
             src: /build/libs/logireports-sso-{{ version }}.jar
             dest: /home/logij/ReportServer/custom/logireports-sso.jar
             owner: root
             group: root
             mode: '0644'

         - name: Run SSO Startup service shutdown script
           ansible.builtin.script: nohup /home/logij/ReportServer/bin/JRServer.sh &

         - name: Run Zoomdata service shutdown script
           ansible.builtin.script: /opt/zoomdata/bin/zdmanage services start