---
## KER - 6/22/2022
- name: Zoomdata Upgrade Cleanup
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Removes old boostrap script
      file:
        path: /opt/bootstrap-zoomdata.run
        state: absent

    - name: update YUM repos
      ansible.builtin.shell: yum -y update

    - name: Download new bootstrap
      ansible.builtin.get_url:
        url: https://composer-repo.logianalytics.com/{{ version }}/bootstrap-zoomdata.run
        dest: /opt/bootstrap-zoomdata.run
        mode: '755'

    - name: Run Zoomdata service shutdown script
      ansible.builtin.script: /opt/zoomdata/bin/zdmanage services stop

    - name: Run kick off bootstrap
        ansible.builtin.script: /opt/bootstrap-zoomdata.run

    - name: Check service status
      ansible.builtin.script: /opt/zoomdata/bin/zdmanage services status
      register: command_result
      failed_when:
        - "'zoomdata-consul is down' in command_result.stderr"
        - "'zoomdata-data-writer-postgresql is down' in command_result.stderr"
        - "'zoomdata-edc-mssql is down' in command_result.stderr"
        - "'zoomdata-edc-postgresql is down' in command_result.stderr"
        - "'zoomdata-edc-rts is down' in command_result.stderr"
        - "'zoomdata-edc-splicemachine is down' in command_result.stderr"
        - "'zoomdata-query-engine is down' in command_result.stderr"
        - "'zoomdata-screenshot-service is down' in command_result.stderr"
        - "'zoomdata is down' in command_result.stderr"