---
## KER - 6/22/2022
- name: Elasticsearch Certificate Cleanup
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Removes wildcard_fivefingerheadpat_com.bundle.old from /etc/elasticsearch
      file:
        path: /etc/elasticsearch/wildcard_fivefingerheadpat_com.bundle.old
        state: absent