---
## KER - 6/22/2022
- name: Elasticsearch Certificate Cleanup
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Removes wildcard_<my_domain>_com.bundle.old from /etc/elasticsearch
      file:
        path: /etc/elasticsearch/wildcard_<my_domain>_com.bundle.old
        state: absent