---
## KER - 6/21/2022
- name: Elasticsearch version update
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Stopping Elasticsearch services
      ansible.builtin.service:
        name: elasticsearch
        state: stopped

    - name: Backup config files
        ansible.builtin.copy:
          remote_src: true
          src: /etc/elasticsearch/elasticsearch.yml
          dest: /etc/elasticsearch/elasticsearch.yml.bkp
        when: check_file_name.stat.exists

    - name: Rotate repo file to enable elasticsearch downloads/updates
        copy:
          remote_src: true
          src: /etc/yum.repo.d/elasticsearch.repo.bkp
          dest: /etc/yum.repo.d/elasticsearch.repo
        when: check_file_name.stat.exists

    - name: Upgrades elasticsearch to latest version available to repo in /etc/yum.repo.d/elasticsearch.repo on target machine
        yum:
          name: elasticsearch
          enablerepo: elasticsearch
          state: latest

    - name: Backup config files
      copy:
        remote_src: true
        src: /etc/elasticsearch/elasticsearch.yml.bkp
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: root
        mode: '0644'
      when: check_file_name.stat.exists

    - name: Rotate repo file to disable elasticsearch downloads/updates
      copy:
        remote_src: true
        src: /etc/yum.repo.d/elasticsearch.repo
        dest: /etc/yum.repo.d/elasticsearch.repo.bkp
    when: check_file_name.stat.exists

      - name: Starting Elasticsearch Service
        ansible.builtin.service:
          name: elasticsearch
          state: started