---
## KER - 6/21/2022
- name: Elasticsearch version update
  hosts: all
  gather_facts: false

  tasks:
    - name: Stop Elasticsearch services
      ansible.builtin.service:
        name: elasticsearch
        state: stopped

    - name: Backup config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/elasticsearch/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml.ansible
        #when: check_file_name.stat.exists
      become: yes
      become_method: su
      become_user: root

    - name: Rotate repo file to enable elasticsearch downloads/updates
      copy:
        remote_src: true
        src: /etc/yum.repo.d/elasticsearch.repo.ansible
        dest: /etc/yum.repo.d/elasticsearch.repo
        #when: check_file_name.stat.exists
      become: yes
      become_method: su
      become_user: root

    - name: Upgrades elasticsearch to latest version available to repo in /etc/yum.repo.d/elasticsearch.repo on target machine
      yum:
        name: elasticsearch
        enablerepo: elasticsearch
        state: latest

    - name: Remove Elasticsearch repo file (delete file)
      ansible.builtin.file:
        path: /etc/yum.repo.d/elasticsearch.repo
        state: absent

    - name: Restore config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/elasticsearch/elasticsearch.yml.ansible
        dest: /etc/elasticsearch/elasticsearch.yml
        #when: check_file_name.stat.exists
      become: yes
      become_method: su
      become_user: root

    - name: Starting Elasticsearch Service
      ansible.builtin.service:
        name: elasticsearch
        state: started