---
## KER - 6/21/2022
- name: Elasticsearch version update
  hosts: all
  gather_facts: false
  become: yes
  #become_method: su
  #become_user: nobody
  #become_flags: '-s /bin/sh'

  tasks:
    - name: Stop Elasticsearch services
      ansible.builtin.service:
        name: elasticsearch
        state: stopped

    - name: Backup config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/elasticsearch/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml.ansible
        #when: check_file_name.stat.exists

    - name: Add elasticsearch repository
      ansible.builtin.yum_repository:
        name: elasticsearch
        description: elasticsearch yum repo
        baseurl: https://artifacts.elastic.co/packages/8.x/yum

    - name: Upgrades elasticsearch to latest version available to repo in /etc/yum.repo.d/elasticsearch.repo on target machine
      yum:
        name: elasticsearch
        enablerepo: elasticsearch
        state: latest

    - name: Remove Elasticsearch repo
      ansible.builtin.yum_repository:
        name: elasticsearch
        state: absent
      #notify: yum-clean-metadata

    - name: Restore config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/elasticsearch/elasticsearch.yml.ansible
        dest: /etc/elasticsearch/elasticsearch.yml
        #when: check_file_name.stat.exists
      become: yes
      #become_method: su
      #become_user: root

    - name: Starting Elasticsearch Service
      ansible.builtin.service:
        name: elasticsearch
        state: started