---
## KER - 8/19/2022
- name: Elasticsearch version update
  hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: Stop Elasticsearch services
      ansible.builtin.service:
        name: elasticsearch
        state: stopped

    - name: Backup config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/elasticsearch/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml.ansible

    - name: Add elasticsearch repository (RedHat)
      ansible.builtin.yum_repository:
        name: elasticsearch
        description: elasticsearch yum repo
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
      when: ansible_os_family == 'RedHat'

    - name: Add elasticsearch repository (Debian)
      ansible.builtin.apt_repository:
        name: elasticsearch
        description: elasticsearch apt repo
        baseurl: https://artifacts.elastic.co/packages/8.x/apt
      when: ansible_os_family == 'Debian'

    - name: Upgrades elasticsearch to latest version available to repo in /etc/yum.repo.d/elasticsearch.repo on target machine (RedHat)
      yum:
        name: elasticsearch
        enablerepo: elasticsearch
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Upgrades elasticsearch to latest version available to repo in /etc/apt/source.list.d/elastic-v8.X.list on target machine (Debian)
      apt:
        name: elasticsearch
        enablerepo: elasticsearch
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Remove Elasticsearch repo (RedHat)
      ansible.builtin.yum_repository:
        name: elasticsearch
        state: absent
      when: ansible_os_family == 'RedHat'

    - name: Remove Elasticsearch repo (Debian)
      ansible.builtin.apt_repository:
        name: elasticsearch
        state: absent
      when: ansible_os_family == 'Debian'

    - name: Restore config files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/elasticsearch/elasticsearch.yml.ansible
        dest: /etc/elasticsearch/elasticsearch.yml
      become: yes

    - name: Restart elasticsearch service on centos, in all cases, also issue daemon-reload to pick up config changes
      ansible.builtin.systemd:
        state: started
        daemon_reload: yes
        name: elasticsearch

    - name: Starting Elasticsearch Service
      ansible.builtin.service:
        name: elasticsearch
        state: started