---
## KER - 6/22/2022
- name: NGINX Certificate Cleanup - Internal
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Removes wildcard_<my_domain>_com.bundle.old from /etc/nginx/ssl/
      file:
        path: /etc/nginx/ssl/wildcard_<my_domain>_com.bundle.old
        state: absent